name: mwc
description: mwc Flutter project.

publish_to: "none"

version: 1.0.0+12
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  aligned_dialog: ^0.0.7
  auto_size_text: 3.0.0
  cached_network_image: ^3.3.1

  dropdown_button2: ^2.3.9
  floating_bottom_navigation_bar: 1.5.2
  flutter_animate: ^4.5.0
  flutter_cache_manager: ^3.3.1
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.7.0
  from_css_color: 2.0.0
  go_router: ^14.2.7
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  google_sign_in_android: ^6.1.22
  google_sign_in_ios: ^5.7.5
  google_sign_in_platform_interface: ^2.4.5
  google_sign_in_web: ^0.12.4
  intl: ^0.18.1
  json_path: ^0.7.1
  page_transition: ^2.1.0
  path_provider: ^2.1.2
  path_provider_android: ^2.2.2
  path_provider_foundation: ^2.3.2
  path_provider_platform_interface: ^2.1.2
  plugin_platform_interface: ^2.1.8
  provider: ^6.1.2
  rxdart: ^0.28.0
  shared_preferences: ^2.2.2
  shared_preferences_android: ^2.2.1
  shared_preferences_platform_interface: ^2.3.2
  shared_preferences_web: ^2.3.0
  sign_in_with_apple: ^6.0.0
  sign_in_with_apple_platform_interface: ^1.0.0
  sign_in_with_apple_web: ^2.0.0
  sqflite: ^2.3.2
  stream_transform: ^2.1.0
  timeago: ^3.6.1
  url_launcher: ^6.3.0
  url_launcher_ios: ^6.3.0
  url_launcher_platform_interface: ^2.3.2
  flutter_keyboard_visibility: ^6.0.0
  http: ^1.2.2
  social_share: ^2.3.1
  pull_to_refresh: ^2.0.0
  flutter_blue_plus: ^1.31.13
  flutter_dash: ^1.0.0
  modal_bottom_sheet: ^3.0.0
  toggle_switch: ^2.1.0
  model_viewer_plus: ^1.7.0
  easy_rich_text: ^2.1.0
  fl_chart: ^0.69.0
  flutter_local_notifications: ^17.1.2

  cupertino_icons: ^1.0.0
  table_calendar: ^3.0.9
  logger: ^2.2.0
  persistent_bottom_nav_bar: ^6.2.1
  retrofit: ^4.4.1
  dio: ^5.7.0
  json_annotation: ^4.0.1
  flutter_decorated_text: ^1.0.14
  colored_text: ^0.0.1
  image_picker: ^1.1.2
  filter_list: ^1.0.0
  location_picker_flutter_map: ^2.1.0
  flutter_compass: ^0.8.0
  flutter_launcher_icons: ^0.13.1
  loop_page_view: ^1.2.5
  flutter_spinkit: ^5.2.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/appicon.png"
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  intl_utils: ^2.5.0
  video_player: ^2.1.15
  flutter_unity_widget: ^2022.2.1
  flutter_flavorizr: ^2.2.3
  permission_handler: ^11.3.1
  http_parser: ^4.0.0
  flutter_webrtc: ^0.11.6+hotfix.1
  socket_io_client: ^2.0.0
  vibration: ^2.0.0
  share_plus: ^10.0.0

flutter_intl:
  enabled: true
  arb_dir: lib/l10n
  template_arbs: lib/l10n/intl_en.arb
  output_dir: lib/generated

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/icons/
    - assets/body3d/
    - assets/bodygrapic/back/female/
    - assets/bodygrapic/back/male/
    - assets/bodygrapic/flat/female/
    - assets/bodygrapic/flat/male/
    - assets/bodygrapic/yo/female/
    - assets/bodygrapic/yo/male/
    - assets/bodygrapic/front/female/
    - assets/bodygrapic/front/male/
    - assets/bodygrapic/left/female/
    - assets/bodygrapic/left/male/
    - assets/bodygrapic/right/female/
    - assets/bodygrapic/right/male/
    - assets/bodygrapic/leftroll/female/
    - assets/bodygrapic/leftroll/male/
    - assets/bodygrapic/rightroll/female/
    - assets/bodygrapic/rightroll/male/
    - assets/bodygrapic/normal/female/
    - assets/bodygrapic/normal/male/
    - assets/text/

  fonts:
    - family: "Pretendard"
      fonts:
        - asset: assets/fonts/Pretendard-Thin.otf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.otf
          weight: 900
